spring:
  datasource: # org.springframework.boot.autoconfigure.jdbc.DataSourceProperties
#    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:p6spy:sqlite:C:\Dev\SQLite\demo_db.db
#    url: jdbc:p6spy:mysql://my_db:5306/demo_db?serverTimezone=Hongkong
#    username: myUser
#    password: p
    driverClassName: com.p6spy.engine.spy.P6SpyDriver
    hikari: # com.zaxxer.hikariHikariDataSource extends HikariConfig
      maximumPoolSize: 3
      maxLifetime: 1500000  # MILLISECONDS
mybatis:
#  # mapper文件位置，如果mapper文件与接口放在相同包路径下则无需此配置
#  mapper-locations: classpath*:com/ozz/**/mapper/**/*.xml
  type-aliases-package: com.ozz.mybatis.model
  type-aliases-super-type: com.ozz.mybatis.model.BaseObject
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    mapUnderscoreToCamelCase: true
conmybatis-plus:
  global-config:
    db-config:
      id-type: AUTO # com.baomidou.mybatisplus.annotation.IdType
