# 配置说明: https://baomidou.com/guide/dynamic-datasource.html#%E6%96%87%E6%A1%A3-documentation
spring:
  datasource:
    dynamic: # com.baomidou.dynamic.datasource.spring.boot.autoconfigure.DynamicDataSourceProperties
      primary: ds #设置默认的数据源或者数据源组,默认值即为master
      strict: false #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候会抛出异常,不启动则使用默认数据源.
      datasource:
        ds: # com.baomidou.dynamic.datasource.spring.boot.autoconfigure.DataSourceProperty
#          type: com.zaxxer.hikari.HikariDataSource
          url: jdbc:p6spy:sqlite:C:\Dev\SQLite\demo_db.db
#          url: jdbc:p6spy:mysql://my_db:5306/demo_db?serverTimezone=Hongkong
#          username: myUser
#          password: p
          driverClassName: com.p6spy.engine.spy.P6SpyDriver
          hikari:
            maxPoolSize: 3
            maxLifetime: 1500000
        ds2:
#          type: com.zaxxer.hikari.HikariDataSource
          url: jdbc:p6spy:sqlite:C:\Dev\SQLite\demo_db2.db
#          url: jdbc:p6spy:mysql://my_db:5306/demo_db2?serverTimezone=Hongkong
#          username: myUser
#          password: p
          driverClassName: com.p6spy.engine.spy.P6SpyDriver
          hikari:
            maxPoolSize: 3
            maxLifetime: 1500000
mybatis:
  type-aliases-package: com.ozz.mybatis.model
  type-aliases-super-type: com.ozz.mybatis.model.BaseObject
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    mapUnderscoreToCamelCase: true

